language: cpp
compiler: gcc
sudo: false
addons:
    apt:
        packages:
            -doxygen
            -libfftw3-single3
            -libfftw3-dev
            -tcsh
            -python-sphinx
install: 
    - wget -q http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
    - tar xzf cmake-3.2.1.tar.gz
    - cd cmake-3.2.1
    - ./configure --prefix=$HOME/cmake
    - make -j 4
    - make install
    - cd ..
    - wget -q ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.1.tar.gz
    - tar xzf gromacs-5.1.tar.gz
    - cd gromacs-5.1
    - mkdir build
    - cd build
    - $HOME/cmake/bin/cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=$HOME/gromacs ..
    - make -j 4
    - make install
    - cd ../..
    - rm -rf gromacs-5.1*
    - cd libgmxcpp
    - source $HOME/gromacs/bin/GMXRC.bash
    - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/gromacs/include
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make -j 4
    - make test
#   - make docs
