language: cpp
compiler: gcc
install: 
    - sudo apt-get update -qq
    - sudo apt-get install doxygen 
    - sudo pip install --upgrade pip
    - sudo pip install sphinx 
    - sudo pip install breathe
    - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.0.4.tar.gz
    - tar xvzf gromacs-5.0.4.tar.gz
    - cd gromacs-5.0.4
    - sed -i 's/cmake_minimum_required(VERSION 2.8.8)/cmake_minimum_required(VERSION 2.8.7)/g' CMakeLists.txt
    - mkdir build
    - cd build
    - cmake ..
    - make
    - sudo make install
    - source /usr/local/gromacs/bin/GMXRC.bash
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make
    - make test
    - make docs
