language: cpp
compiler: gcc
install: 
    - sudo apt-get update -qq
    - sudo apt-get install doxygen libfftw3-3 libfftw3-dev tcsh
    - sudo pip install --upgrade pip
    - sudo pip install sphinx 
    - sudo pip install breathe
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
    - tar xvzf cmake-3.2.1.tar.gz
    - cd cmake-3.2.1
    - ./configure
    - make -j 4
    - sudo make install
    - cd ..
    - rm -rf cmake-3.2.1*
    - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.0.4.tar.gz
    - tar xvzf gromacs-5.0.4.tar.gz
    - cd gromacs-5.0.4
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - sudo make install
    - cd ..
    - rm -rf gromacs-5.0.4*
    - source /usr/local/gromacs/bin/GMXRC.bash
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make
    - make test
    - make docs
