language: cpp
compiler:
  - gcc
  - clang
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make
    - cd ../tests
    - g++ tests.cpp ../build/src/lib/libgmxcpp.so -o tests -I../include
    - ./tests
