language: cpp
compiler: gcc
sudo: false
addons:
    apt:
        packages:
            -doxygen
            -tcsh
            -python-sphinx
            -cmake
install: 
    - wget -g https://cmake.org/files/v3.4/cmake-3.4.1.tar.gz
    - tar xzf cmake-3.4.1.tar.gz
    - cd cmake-3.4.1
    - ./configure --prefix=$HOME/cmake/
    - make
    - make install
    - wget -q ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.1.1.tar.gz
    - tar xzf gromacs-5.1.1.tar.gz
    - cd gromacs-5.1.1
    - mkdir build
    - cd build
    - $HOME/cmake/bin/cmake .. -Wno-dev -DCMAKE_INSTALL_PREFIX=$HOME/gromacs -DGMX_BUILD_OWN_FFTW=ON
    - make -j 4
    - make install
    - cd ../..
    - rm -rf gromacs-5.1.1*
    - source $HOME/gromacs/bin/GMXRC.bash
    - export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$HOME/gromacs/include
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make -j 4
    - make test
#   - make docs
