language: cpp
compiler: gcc
install: 
    - sudo apt-get update -qq
    - sudo apt-get install doxygen libfftw3-3 libfftw3-dev tcsh -qq
    - sudo pip install --upgrade pip -q
    - sudo pip install sphinx -q
    - sudo pip install breathe -q
    - cd ..
    - wget -q http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
    - tar xzf cmake-3.2.1.tar.gz
    - cd cmake-3.2.1
    - ./configure
    - make -j 4
    - sudo make install
    - cd ..
    - rm -rf cmake-3.2.1*
    - wget -q ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.0.4.tar.gz
    - tar xzf gromacs-5.0.4.tar.gz
    - cd gromacs-5.0.4
    - mkdir build
    - cd build
    - cmake -Wno-dev ..
    - make -j 4
    - sudo make install
    - cd ../..
    - rm -rf gromacs-5.0.4*
    - source /usr/local/gromacs/bin/GMXRC.bash
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make
    - make test
    - make docs
