language: cpp
compiler: gcc
install: 
    - sudo apt-get update -qq
    - sudo apt-get install doxygen 
    - sudo apt-get install gromacs
    - sudo pip install --upgrade pip
    - sudo pip install sphinx 
    - sudo pip install breathe
    - source /usr/local/bin/GMXRC.bash
script: 
    - mkdir build 
    - cd build
    - cmake .. 
    - make
    - make test
    - make docs
